name: CI

on:
    push:
        branches:
            - master

env:
    REGISTRY: "zothe"
    IMAGE_NAME: "telegram-bot"
    CONTAINER_NAME: "tg-bot"

jobs:
    build_and_push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout master
              uses: actions/checkout@v2

            - name: Build container image
              run:
                  docker build -t $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo
                  $GITHUB_SHA | head -c7) .
            - name: Login to Docker hub
              run:
                  docker login -u ${{ secrets.DOCKER_LOGIN}} -p ${{
                  secrets.DOCKER_PASSWORD}}
            - name: Push image to Docker hub
              run:
                  docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo
                  $GITHUB_SHA | head -c7)

    deploy:
        runs-on: ubuntu-latest
        needs: build_and_push

        steps:
            - name: Deploy to VPS via SSH action
              uses: appleboy/ssh-action@v0.1.3
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  envs: IMAGE_NAME,REGISTRY,GITHUB_SHA,CONTAINER_NAME
                  script: |
                      # Login into Docker hub
                      docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}
                      # Stop running container
                      docker stop $(echo $CONTAINER_NAME)
                      # Remove old container
                      docker rm $(echo $CONTAINER_NAME)
                      # Set env variables
                      export BOT_TOKEN=${{ secrets.BOT_TOKEN }}
                      # Run a new container from a new image
                      docker run -e BOT_TOKEN -d \
                      --restart always \
                      --publish 80:80 \
                      --name $(echo $CONTAINER_NAME) \
                      $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)
